// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4GdT9Qv4Gc7_JW4zXOJB8WnopRcTeEm0',
    appId: '1:190535714842:web:6cdcc9a5522a3b447be9a3',
    messagingSenderId: '190535714842',
    projectId: 'nandogami-45016',
    authDomain: 'nandogami-45016.firebaseapp.com',
    databaseURL: 'https://nandogami-45016-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nandogami-45016.firebasestorage.app',
    measurementId: 'G-PYT9W7H87D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMGiYIV4XL6y5d8VtpER5lswpSfPxE6JQ',
    appId: '1:190535714842:android:3ec9b1b47eea08837be9a3',
    messagingSenderId: '190535714842',
    projectId: 'nandogami-45016',
    databaseURL: 'https://nandogami-45016-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nandogami-45016.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGtTzkFB4bKMOTHEil32OXp9ad_xGty9k',
    appId: '1:190535714842:ios:984b6dbf8236a9bb7be9a3',
    messagingSenderId: '190535714842',
    projectId: 'nandogami-45016',
    databaseURL: 'https://nandogami-45016-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nandogami-45016.firebasestorage.app',
    iosBundleId: 'com.example.nandogamiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGtTzkFB4bKMOTHEil32OXp9ad_xGty9k',
    appId: '1:190535714842:ios:984b6dbf8236a9bb7be9a3',
    messagingSenderId: '190535714842',
    projectId: 'nandogami-45016',
    databaseURL: 'https://nandogami-45016-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nandogami-45016.firebasestorage.app',
    iosBundleId: 'com.example.nandogamiFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4GdT9Qv4Gc7_JW4zXOJB8WnopRcTeEm0',
    appId: '1:190535714842:web:05ed73edd1b5444f7be9a3',
    messagingSenderId: '190535714842',
    projectId: 'nandogami-45016',
    authDomain: 'nandogami-45016.firebaseapp.com',
    databaseURL: 'https://nandogami-45016-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nandogami-45016.firebasestorage.app',
    measurementId: 'G-VBYJFE73PE',
  );
}
